### ISSUE TITLE
Urls for samples does not exist. Github 404.

### ISSUE THREAD

**Issue by kamilk91** [SciSharp/TensorFlow.NET#291] opened 2019-07-13 15:05 UTC
```
Example runner will download all the required files like training data and model pb files.

Hello World
Basic Operations
Linear Regression
Logistic Regression
Nearest Neighbor
Naive Bayes Classification
Full Connected Neural Network
Image Recognition
K-means Clustering
NN XOR
Object Detection
Text Classification
CNN Text Classification
MNIST CNN
Named Entity Recognition
Transfer Learning for Image Classification in InceptionV3
More troubleshooting of running example refer here.
```
From sample page. Any link does not work.

**Comment by Oceania2018** [comment] 2019-07-13 15:27
It works on my computer.

![image](https://user-images.githubusercontent.com/1705364/61173425-dc1b6a00-a558-11e9-9190-b3339b191a46.png)

**Comment by henon** [comment] 2019-07-14 08:43
The problem was caused by my renaming of misspelled folders like `ImageProcess` --> `ImageProcessing`  which I committed yesterday. Fixing the readme now.

**Closed by henon** 2019-07-14 08:43 UTC
