### ISSUE TITLE
Creating DnCNN

### ISSUE THREAD

**Issue by Jamaslab** [SciSharp/TensorFlow.NET#367] opened 2019-08-28 09:50 UTC
Hello,
I'm trying to create a DnCNN. I wrote the following code (a bit confused, there are a lot of testing things).
``` C#
public class DnCNN {
        private const int batch_size = 128;

        Tensor X, Y_, Y;
        Tensor loss;
        Operation optimizer;

        Session sess;

        public DnCNN() {
            sess = new Session();
            tf_with(tf.name_scope("Input"), delegate {
                Y_ = tf.placeholder(tf.float32, shape: (-1, 477, 500, 3), name: "clean_image");
                X = tf.placeholder(tf.float32, shape: (-1, 477, 500, 3));
            });

            var is_training = tf.placeholder(tf.@bool, name: "is_training");            
            Y = BuildModel(X);

            tf_with(tf.variable_scope("Train"), delegate {
                tf_with(tf.variable_scope("Loss"), delegate {
                    loss = (1.0 / batch_size) * tf.nn.relu(Y_ - Y);
                });

                tf_with(tf.variable_scope("Optimizer"), delegate {
                    optimizer = tf.train.AdamOptimizer(0.001f, name: "AdamOptimizer").minimize(loss);
                });
            });

            var init = tf.global_variables_initializer();
            sess.run(init);
        }

        private Tensor BuildModel(Tensor input, bool is_training = true) {
            Tensor output = null;
            tf_with(tf.variable_scope("block1"), delegate {
                output = tf.layers.conv2d(input, 64, new int[] { 3, 3 }, padding: "same");
            });

            for (int i = 2; i < 20; i++) {
                tf_with(tf.variable_scope("block"+i), delegate {
                    output = tf.layers.conv2d(output, 64, new int[] { 3, 3 }, name:"conv"+i, padding: "same", use_bias: false);
                    //output = tf.nn.relu(tf.layers.batch_normalization(output, trainable: is_training));
                });
            }

            tf_with(tf.variable_scope("block20"), delegate {
                output = tf.layers.conv2d(output, 3, new int[] { 3, 3 }, padding: "same", use_bias: false);
            });

            return input - output;
        }

        public void Train(List<Bitmap> inputImages, List<Bitmap> outputImages, int epochs=1) {
            NDArray x_train = array(inputImages[0]);
            NDArray y_train = array(outputImages[0]);

            var sw = new Stopwatch();
            sw.Start();
            for (int i = 0; i < epochs; i++) {
                sess.run(optimizer, (X, x_train), (Y_, y_train));
                // Calculate and display the batch loss and accuracy
                var result = sess.run(new[] { loss }, new FeedItem(X, x_train), new FeedItem(Y_, y_train));
                var loss_val = result[0];
                print($"iter {i.ToString("000")}: Loss={loss_val.ToString()} {sw.ElapsedMilliseconds}ms");
                sw.Restart();
            }
        }

        private NDArray BuildFromImageList(List<Bitmap> images) {
            var imagesArrays = new List<NDArray>();
            foreach (var image in images) {
                imagesArrays.Add(array(image));
            }

            NDArray x = new NDArray(imagesArrays.ToArray());
            var dataset = x.reshape(x.shape[0], images[0].Width, images[1].Height, 3).astype(np.float32);
            return dataset;
        }

        private static NDArray array(Bitmap image) {
            var imageArray = new NDArray(typeof(Byte));
            var bmpd = image.LockBits(new System.Drawing.Rectangle(0, 0, image.Width, image.Height), System.Drawing.Imaging.ImageLockMode.ReadOnly, image.PixelFormat);
            var dataSize = bmpd.Stride * bmpd.Height;
            var bytes = new byte[dataSize];
            System.Runtime.InteropServices.Marshal.Copy(bmpd.Scan0, bytes, 0, dataSize);
            image.UnlockBits(bmpd);

            imageArray = new NDArray(bytes, new Shape(1, bmpd.Height, bmpd.Width, 3));

            return imageArray;
        }
}
```

When I try to run the learn (I get only the first image for simplicity), it returns a memory corruption exception on `sess.run(optimizer, (X, x_train), (Y_, y_train));`.

I suppose this comes from badly initializing something, but I'm struggling to understand what. Could somebody help me?

**Comment by Nucs** [comment] 2019-08-28 09:58
Are you using master branch or latest nuget package?

**Comment by Jamaslab** [comment] 2019-08-28 11:30
I'm using the latest nuget package. Attached you can find the image i'm using for testing the code. It's just a random image that I give in input and in output for testing the network. In future I'd like to have dynamic resolutions in input/output (I don't know if it is possible). I will try to run the code with the latest master

![JPEG_example_flower](https://user-images.githubusercontent.com/7974047/63852114-df977300-c997-11e9-88c3-0d998e1865e1.jpg)

**Comment by Jamaslab** [comment] 2019-08-28 11:49
Ok, I just run it with the latest master and I get the same error.
The error comes from here

```
c_api.TF_SessionRun(_handle,
                run_options: null,
                inputs: feed_dict.Select(f => f.Key).ToArray(),
                input_values: feed_dict.Select(f => (IntPtr)f.Value).ToArray(),
                ninputs: feed_dict.Length,
                outputs: fetch_list,
                output_values: output_values,
                noutputs: fetch_list.Length,
                target_opers: target_list.Select(f => (IntPtr)f).ToArray(),
                ntargets: target_list.Count,
                run_metadata: IntPtr.Zero,
                status: status);
```

However, I noticed something. If I attempt to create the session using a Graph in the following way
```
Graph g = new Graph(Y_);
 sess = new Session(g);
 var init = tf.global_variables_initializer();
 sess.run(init);
```
I get the AccessViolationException already in `var init = tf.global_variables_initializer();`, so I'm more worried I'm doing something wrong rather than a bug in the library.

**Comment by Nucs** [comment] 2019-08-28 12:02
I have tested this against our development branch but I assume the solution should be the same on nuget package version.
The problem is within this line:
``` C#
sess.run(optimizer, (X, x_train), (Y_, y_train));
```
The fed items are expected to be of type `Tensor` but you pass in NDArray. In python that would be valid and we'll probably add a resolving internally.
Change this line to the following and your code will run:
``` C#
sess.run(optimizer, (X, new Tensor(x_train)), (Y_, new Tensor(y_train)));
```

**Comment by Nucs** [comment] 2019-08-28 12:04
And because your inputs are expected to be `tf.float32` but the `NDArray` is `uint8/byte`,
``` C#
            tf_with(tf.name_scope("Input"), delegate {
                Y_ = tf.placeholder(tf.float32, shape: (-1, 477, 500, 3), name: "clean_image");
                X = tf.placeholder(tf.float32, shape: (-1, 477, 500, 3));
            });
```
Change the following lines:
``` C#
            NDArray x_train = array(inputImages[0]).astype(NPTypeCode.Single); //we cast because expected input is tf.float32
            NDArray y_train = array(outputImages[0]).astype(NPTypeCode.Single); //we cast because expected input is tf.float32
```

**Comment by Jamaslab** [comment] 2019-08-28 12:09
It works, thank you very much. Do you know how could i remove the dependency from the resolution in the Input and output layers shape?

**Comment by Nucs** [comment] 2019-08-28 12:24
I'm not  a pro when it comes to image classification but I do know that image size is a difficult problem because of the nature of the algorithms,
you can't simply have a single model to match all possible sizes; mathematically that's impossible because the CNN blocks won't match since the number of weights and biases are dependent on the input shape.

What usually is done is either resize using `tf.image.resize_bilinear` to a fixed size ([source](https://stackoverflow.com/questions/47929557/tensorflow-cnn-training-images-are-all-different-sizes)) or have couple of models for different 'categorical' sizes so you can resize to the closest resolution. This does increase complexity and training time but will work if you really need to support different sizes.

Even in algorithms like `GAN` which takes in an image and outputs an image, the size is fixed ([source](https://github.com/pytorch/examples/issues/70)).

**Comment by Jamaslab** [comment] 2019-08-28 12:30
Perfect! thank you very much for your support and congratulations for the great project

**Comment by Nucs** [comment] 2019-08-28 12:35
Happy to help.

**Closed by Nucs** 2019-08-28 12:35 UTC
Labels: bug
