### ISSUE TITLE
Cannot load Tensorflow DLL error.

### ISSUE THREAD

**Issue by JTrotta** [SciSharp/TensorFlow.NET#144] opened 2019-01-29 10:41 UTC
Any idea? obviously tensorflow.dll is in bin folder

`Setting Eager mode...
System.TypeInitializationException: The type initializer for 'Tensorflow.tf' thr
ew an exception. ---> System.DllNotFoundException: Unable to load DLL 'tensorflo
w' or one of its dependencies: Exception from HRESULT: 0xC000001D
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-maste
r\src\TensorFlowNET.Core\Graphs\Graph.cs:line 37
   at Tensorflow.tf..cctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\
src\TensorFlowNET.Core\tf.cs:line 18
   --- End of inner exception stack trace ---
   at Tensorflow.tf.enable_eager_execution() in C:\Users\Sviluppo\Desktop\Tensor
Flow.NET-master\src\TensorFlowNET.Core\tf.cs:line 33
   at TensorFlowNET.Examples.BasicEagerApi.Run() in C:\Users\Sviluppo\Desktop\Te
nsorFlow.NET-master\test\TensorFlowNET.Examples\BasicEagerApi.cs:line 19
   at TensorFlowNET.Examples.Program.Main(String[] args) in C:\Users\Sviluppo\De
sktop\TensorFlow.NET-master\test\TensorFlowNET.Examples\Program.cs:line 21
System.TypeInitializationException: The type initializer for 'Tensorflow.tf' thr
ew an exception. ---> System.DllNotFoundException: Unable to load DLL 'tensorflo
w' or one of its dependencies: Exception from HRESULT: 0xC000001D
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-maste
r\src\TensorFlowNET.Core\Graphs\Graph.cs:line 37
   at Tensorflow.tf..cctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\
src\TensorFlowNET.Core\tf.cs:line 18
   --- End of inner exception stack trace ---
   at Tensorflow.tf.Graph() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\s
rc\TensorFlowNET.Core\tf.cs:line 45
   at Tensorflow.ops.get_default_graph() in C:\Users\Sviluppo\Desktop\TensorFlow
.NET-master\src\TensorFlowNET.Core\ops.py.cs:line 48
   at Tensorflow.constant_op.Constant(NDArray nd, String name, Boolean verify_sh
ape) in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\src\TensorFlowNET.Core\T
ensors\constant_op.cs:line 24
   at Tensorflow.tf.constant(NDArray nd, String name, Boolean verify_shape) in C
:\Users\Sviluppo\Desktop\TensorFlow.NET-master\src\TensorFlowNET.Core\Tensors\tf
.constant.cs:line 12
   at TensorFlowNET.Examples.BasicOperations.Run() in C:\Users\Sviluppo\Desktop\
TensorFlow.NET-master\test\TensorFlowNET.Examples\BasicOperations.cs:line 22
   at TensorFlowNET.Examples.Program.Main(String[] args) in C:\Users\Sviluppo\De
sktop\TensorFlow.NET-master\test\TensorFlowNET.Examples\Program.cs:line 21
System.TypeInitializationException: The type initializer for 'Tensorflow.tf' thr
ew an exception. ---> System.DllNotFoundException: Unable to load DLL 'tensorflo
w' or one of its dependencies: Exception from HRESULT: 0xC000001D
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-maste
r\src\TensorFlowNET.Core\Graphs\Graph.cs:line 37
   at Tensorflow.tf..cctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\
src\TensorFlowNET.Core\tf.cs:line 18
   --- End of inner exception stack trace ---
   at Tensorflow.tf.Graph() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\s
rc\TensorFlowNET.Core\tf.cs:line 45
   at Tensorflow.ops.get_default_graph() in C:\Users\Sviluppo\Desktop\TensorFlow
.NET-master\src\TensorFlowNET.Core\ops.py.cs:line 48
   at Tensorflow.constant_op.Constant(NDArray nd, String name, Boolean verify_sh
ape) in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\src\TensorFlowNET.Core\T
ensors\constant_op.cs:line 24
   at Tensorflow.tf.constant(NDArray nd, String name, Boolean verify_shape) in C
:\Users\Sviluppo\Desktop\TensorFlow.NET-master\src\TensorFlowNET.Core\Tensors\tf
.constant.cs:line 12
   at TensorFlowNET.Examples.HelloWorld.Run() in C:\Users\Sviluppo\Desktop\Tenso
rFlow.NET-master\test\TensorFlowNET.Examples\HelloWorld.cs:line 21
   at TensorFlowNET.Examples.Program.Main(String[] args) in C:\Users\Sviluppo\De
sktop\TensorFlow.NET-master\test\TensorFlowNET.Examples\Program.cs:line 21
System.TypeInitializationException: The type initializer for 'Tensorflow.tf' thr
ew an exception. ---> System.DllNotFoundException: Unable to load DLL 'tensorflo
w' or one of its dependencies: Exception from HRESULT: 0xC000001D
   at Tensorflow.c_api.TF_NewGraph()
   at Tensorflow.Graph..ctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-maste
r\src\TensorFlowNET.Core\Graphs\Graph.cs:line 37
   at Tensorflow.tf..cctor() in C:\Users\Sviluppo\Desktop\TensorFlow.NET-master\
src\TensorFlowNET.Core\tf.cs:line 18
   --- End of inner exception stack trace ---
   at TensorFlowNET.Examples.LinearRegression.Run() in C:\Users\Sviluppo\Desktop
\TensorFlow.NET-master\test\TensorFlowNET.Examples\LinearRegression.cs:line 32
   at TensorFlowNET.Examples.Program.Main(String[] args) in C:\Users\Sviluppo\De
sktop\TensorFlow.NET-master\test\TensorFlowNET.Examples\Program.cs:line 21
`

**Comment by Oceania2018** [comment] 2019-01-29 13:31
@JTrotta I noticed there is a space in the lib name.
![image](https://user-images.githubusercontent.com/1705364/51911558-c42f9f80-2397-11e9-93af-9e7c2a08071c.png)

Please check the dll name:
![image](https://user-images.githubusercontent.com/1705364/51911607-e75a4f00-2397-11e9-9108-ec4033c4d3db.png)

**Comment by JTrotta** [comment] 2019-01-29 14:15
@Oceania2018 No. The space is just a copy and paste error. The question is much more complicated.
It seems that on some processor some Tensorfow dll does not work, because it lacks of AVX support, have a  look here [https://github.com/fo40225/tensorflow-windows-wheel](url).

Now I'm using a custom DLL from [https://github.com/fo40225/tensorflow-windows-wheel](url), and it'working. But during session dispose I receive a new error:
![image](https://user-images.githubusercontent.com/2145654/51914202-93238f00-23d8-11e9-8171-45a1b5c0a6f9.png)

Any help on this?

**Comment by Oceania2018** [comment] 2019-01-29 14:52
@JTrotta I use Windows 10 and compile the latest TensorFlow from source code. I've tested on several machines. So what's your environment? Actually, I can't open the link in your above post.

Did you try the simplest test like in the `public void ScalarConst()`?

**Comment by JTrotta** [comment] 2019-01-29 15:10
@Oceania2018 I just updated links.
Yes, the error you see in picture, raises using this basic instructions:
`            // Launch the default graph.
            using(sess = tf.Session())
            {
                var feed_dict = new Dictionary<Tensor, NDArray>();
                feed_dict.Add(a, (short)2);
                feed_dict.Add(b, (short)3);
                // Run every operation with variable input
                Console.WriteLine($"Addition with variables: {sess.run(add, feed_dict)}");
                Console.WriteLine($"Multiplication with variables: {sess.run(mul, feed_dict)}");
            }` 

My enviroment is W7, with : 
![image](https://user-images.githubusercontent.com/2145654/51917681-5cea0d80-23e0-11e9-96bf-5690978cf00c.png)

**Comment by Oceania2018** [comment] 2019-01-29 16:02
@JTrotta Try to use 1.12 download from https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.12.0.zip

I just pushed some changes. pull and retry.

**Comment by Oceania2018** [comment] 2019-01-29 16:04
@JTrotta Are you running `BasicOperations` in TensorFlowNET.Examples ?

**Comment by JTrotta** [comment] 2019-01-29 16:28
@Oceania2018 Yes basic operations...Just trying ....

**Comment by Oceania2018** [comment] 2019-01-29 16:46
@JTrotta Can you check if the `_handle` of the `Session` is `IntPtr.Zero`? I can't reproduce on my local.

**Comment by JTrotta** [comment] 2019-01-29 17:23
@Oceania2018 It does not seem:
![image](https://user-images.githubusercontent.com/2145654/51927083-0508d200-23f3-11e9-969c-6263e095076e.png)

**Comment by Oceania2018** [comment] 2019-01-29 18:47
@JTrotta It's not an empty pointer. Will investigate more for this issue. Thanks for using TensorFlow.NET.

**Comment by Oceania2018** [comment] 2019-01-30 01:23
@JTrotta Can you try again? Don't forget to pull latest code.

**Comment by JTrotta** [comment] 2019-01-30 08:51
@Oceania2018 @dotChris90 , can't do it this morning , I will try this evening (in about 9 hours from now). Sorry and thank you for your work.

**Comment by JTrotta** [comment] 2019-01-30 16:19
@Oceania2018 @dotChris90 Hello, just tried. 
using the tensorflow.dll "unmodified" it does not work, I got the error "dll not found".
Using the tensorflow.dll "modified" form [ https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.12.0.zip]( https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.12.0.zip) it works, the dispose error disappeared, but look here:
![image](https://user-images.githubusercontent.com/2145654/51995527-2b8e4200-24b3-11e9-8994-9f74406161c9.png)

What's the format exception?

**Comment by Oceania2018** [comment] 2019-01-30 17:09
@JTrotta Basically, You are running TF.NET successfully. I just fixed the `HelloWorld` example.

**Comment by Oceania2018** [comment] 2019-01-30 17:10
Will close this issue. If you have another issue, please create new one. @JTrotta Thanks for testing.

**Closed by Oceania2018** 2019-01-30 17:10 UTC
Labels: bug

**Comment by pardont** [comment] 2020-11-25 08:00
Hi, @JTrotta how to get tensorflow.dll from https://github.com/fo40225/tensorflow-windows-wheel ? 

Thanks.
